import { CSSProperties } from './type';

export const cssPropList: (keyof CSSProperties)[] = [
  'accentColor',
  'alignContent',
  'alignItems',
  'alignSelf',
  'alignmentBaseline',
  'all',
  'animation',
  'animationDelay',
  'animationDirection',
  'animationDuration',
  'animationFillMode',
  'animationIterationCount',
  'animationName',
  'animationPlayState',
  'animationTimingFunction',
  'appearance',
  'aspectRatio',
  'backfaceVisibility',
  'background',
  'backgroundAttachment',
  'backgroundBlendMode',
  'backgroundClip',
  'backgroundColor',
  'backgroundImage',
  'backgroundOrigin',
  'backgroundPosition',
  'backgroundPositionX',
  'backgroundPositionY',
  'backgroundRepeat',
  'backgroundSize',
  'baselineShift',
  'blockSize',
  'border',
  'borderBlock',
  'borderBlockColor',
  'borderBlockEnd',
  'borderBlockEndColor',
  'borderBlockEndStyle',
  'borderBlockEndWidth',
  'borderBlockStart',
  'borderBlockStartColor',
  'borderBlockStartStyle',
  'borderBlockStartWidth',
  'borderBlockStyle',
  'borderBlockWidth',
  'borderBottom',
  'borderBottomColor',
  'borderBottomLeftRadius',
  'borderBottomRightRadius',
  'borderBottomStyle',
  'borderBottomWidth',
  'borderCollapse',
  'borderColor',
  'borderEndEndRadius',
  'borderEndStartRadius',
  'borderImage',
  'borderImageOutset',
  'borderImageRepeat',
  'borderImageSlice',
  'borderImageSource',
  'borderImageWidth',
  'borderInline',
  'borderInlineColor',
  'borderInlineEnd',
  'borderInlineEndColor',
  'borderInlineEndStyle',
  'borderInlineEndWidth',
  'borderInlineStart',
  'borderInlineStartColor',
  'borderInlineStartStyle',
  'borderInlineStartWidth',
  'borderInlineStyle',
  'borderInlineWidth',
  'borderLeft',
  'borderLeftColor',
  'borderLeftStyle',
  'borderLeftWidth',
  'borderRadius',
  'borderRight',
  'borderRightColor',
  'borderRightStyle',
  'borderRightWidth',
  'borderSpacing',
  'borderStartEndRadius',
  'borderStartStartRadius',
  'borderStyle',
  'borderTop',
  'borderTopColor',
  'borderTopLeftRadius',
  'borderTopRightRadius',
  'borderTopStyle',
  'borderTopWidth',
  'borderWidth',
  'bottom',
  'boxShadow',
  'boxSizing',
  'breakAfter',
  'breakBefore',
  'breakInside',
  'captionSide',
  'caretColor',
  'clear',
  /** @deprecated */
  'clip',
  'clipPath',
  'clipRule',
  'color',
  'colorInterpolation',
  // 'colorInterpolationFilters',
  'colorScheme',
  'columnCount',
  'columnFill',
  'columnGap',
  'columnRule',
  'columnRuleColor',
  'columnRuleStyle',
  'columnRuleWidth',
  'columnSpan',
  'columnWidth',
  'columns',
  'contain',
  'content',
  'counterIncrement',
  'counterReset',
  'counterSet',
  // 'cssFloat',
  // 'cssText',
  'cursor',
  'direction',
  'display',
  'dominantBaseline',
  'emptyCells',
  'fill',
  'fillOpacity',
  'fillRule',
  'filter',
  'flex',
  'flexBasis',
  'flexDirection',
  'flexFlow',
  'flexGrow',
  'flexShrink',
  'flexWrap',
  'float',
  'floodColor',
  'floodOpacity',
  'font',
  'fontFamily',
  'fontFeatureSettings',
  'fontKerning',
  'fontOpticalSizing',
  'fontSize',
  'fontSizeAdjust',
  'fontStretch',
  'fontStyle',
  'fontSynthesis',
  'fontVariant',
  /** @deprecated */
  'fontVariantAlternates',
  'fontVariantCaps',
  'fontVariantEastAsian',
  'fontVariantLigatures',
  'fontVariantNumeric',
  'fontVariantPosition',
  'fontVariationSettings',
  'fontWeight',
  'gap',
  'grid',
  'gridArea',
  'gridAutoColumns',
  'gridAutoFlow',
  'gridAutoRows',
  'gridColumn',
  'gridColumnEnd',
  /** @deprecated This is a legacy alias of `columnGap`. */
  'gridColumnGap',
  'gridColumnStart',
  /** @deprecated This is a legacy alias of `gap`. */
  'gridGap',
  'gridRow',
  'gridRowEnd',
  /** @deprecated This is a legacy alias of `rowGap`. */
  'gridRowGap',
  'gridRowStart',
  'gridTemplate',
  'gridTemplateAreas',
  'gridTemplateColumns',
  'gridTemplateRows',
  'height',
  'hyphens',
  /** @deprecated */
  'imageOrientation',
  'imageRendering',
  'inlineSize',
  'inset',
  'insetBlock',
  'insetBlockEnd',
  'insetBlockStart',
  'insetInline',
  'insetInlineEnd',
  'insetInlineStart',
  'isolation',
  'justifyContent',
  'justifyItems',
  'justifySelf',
  'left',
  'letterSpacing',
  'lightingColor',
  'lineBreak',
  'lineHeight',
  'listStyle',
  'listStyleImage',
  'listStylePosition',
  'listStyleType',
  'margin',
  'marginBlock',
  'marginBlockEnd',
  'marginBlockStart',
  'marginBottom',
  'marginInline',
  'marginInlineEnd',
  'marginInlineStart',
  'marginLeft',
  'marginRight',
  'marginTop',
  'marker',
  'markerEnd',
  'markerMid',
  'markerStart',
  'mask',
  'maskType',
  'maxBlockSize',
  'maxHeight',
  'maxInlineSize',
  'maxWidth',
  'minBlockSize',
  'minHeight',
  'minInlineSize',
  'minWidth',
  'mixBlendMode',
  'objectFit',
  'objectPosition',
  'offset',
  'offsetAnchor',
  'offsetDistance',
  'offsetPath',
  'offsetRotate',
  'opacity',
  'order',
  'orphans',
  'outline',
  'outlineColor',
  'outlineOffset',
  'outlineStyle',
  'outlineWidth',
  'overflow',
  'overflowAnchor',
  'overflowWrap',
  'overflowX',
  'overflowY',
  'overscrollBehavior',
  'overscrollBehaviorBlock',
  'overscrollBehaviorInline',
  'overscrollBehaviorX',
  'overscrollBehaviorY',
  'padding',
  'paddingBlock',
  'paddingBlockEnd',
  'paddingBlockStart',
  'paddingBottom',
  'paddingInline',
  'paddingInlineEnd',
  'paddingInlineStart',
  'paddingLeft',
  'paddingRight',
  'paddingTop',
  'pageBreakAfter',
  'pageBreakBefore',
  'pageBreakInside',
  'paintOrder',
  'perspective',
  'perspectiveOrigin',
  'placeContent',
  'placeItems',
  'placeSelf',
  'pointerEvents',
  'position',
  'quotes',
  'resize',
  'right',
  'rotate',
  'rowGap',
  'rubyPosition',
  'scale',
  'scrollBehavior',
  'scrollMargin',
  'scrollMarginBlock',
  'scrollMarginBlockEnd',
  'scrollMarginBlockStart',
  'scrollMarginBottom',
  'scrollMarginInline',
  'scrollMarginInlineEnd',
  'scrollMarginInlineStart',
  'scrollMarginLeft',
  'scrollMarginRight',
  'scrollMarginTop',
  'scrollPadding',
  'scrollPaddingBlock',
  'scrollPaddingBlockEnd',
  'scrollPaddingBlockStart',
  'scrollPaddingBottom',
  'scrollPaddingInline',
  'scrollPaddingInlineEnd',
  'scrollPaddingInlineStart',
  'scrollPaddingLeft',
  'scrollPaddingRight',
  'scrollPaddingTop',
  'scrollSnapAlign',
  'scrollSnapStop',
  'scrollSnapType',
  'shapeImageThreshold',
  'shapeMargin',
  'shapeOutside',
  'shapeRendering',
  'stopColor',
  'stopOpacity',
  'stroke',
  'strokeDasharray',
  'strokeDashoffset',
  'strokeLinecap',
  'strokeLinejoin',
  'strokeMiterlimit',
  'strokeOpacity',
  'strokeWidth',
  'tabSize',
  'tableLayout',
  'textAlign',
  'textAlignLast',
  'textAnchor',
  'textCombineUpright',
  'textDecoration',
  'textDecorationColor',
  'textDecorationLine',
  'textDecorationSkipInk',
  'textDecorationStyle',
  'textDecorationThickness',
  'textEmphasis',
  'textEmphasisColor',
  'textEmphasisPosition',
  'textEmphasisStyle',
  'textIndent',
  'textOrientation',
  'textOverflow',
  'textRendering',
  'textShadow',
  'textTransform',
  'textUnderlineOffset',
  'textUnderlinePosition',
  'top',
  'touchAction',
  'transform',
  'transformBox',
  'transformOrigin',
  'transformStyle',
  'transition',
  'transitionDelay',
  'transitionDuration',
  'transitionProperty',
  'transitionTimingFunction',
  'translate',
  'unicodeBidi',
  'userSelect',
  'verticalAlign',
  'visibility',
  /** @deprecated This is a legacy alias of `alignContent`. */
  // 'webkitAlignContent',
  /** @deprecated This is a legacy alias of `alignItems`. */
  // 'webkitAlignItems',
  /** @deprecated This is a legacy alias of `alignSelf`. */
  // 'webkitAlignSelf',
  /** @deprecated This is a legacy alias of `animation`. */
  // 'webkitAnimation',
  /** @deprecated This is a legacy alias of `animationDelay`. */
  // 'webkitAnimationDelay',
  /** @deprecated This is a legacy alias of `animationDirection`. */
  // 'webkitAnimationDirection',
  /** @deprecated This is a legacy alias of `animationDuration`. */
  // 'webkitAnimationDuration',
  /** @deprecated This is a legacy alias of `animationFillMode`. */
  // 'webkitAnimationFillMode',
  /** @deprecated This is a legacy alias of `animationIterationCount`. */
  // 'webkitAnimationIterationCount',
  /** @deprecated This is a legacy alias of `animationName`. */
  // 'webkitAnimationName',
  /** @deprecated This is a legacy alias of `animationPlayState`. */
  // 'webkitAnimationPlayState',
  /** @deprecated This is a legacy alias of `animationTimingFunction`. */
  // 'webkitAnimationTimingFunction',
  /** @deprecated This is a legacy alias of `appearance`. */
  // 'webkitAppearance',
  /** @deprecated This is a legacy alias of `backfaceVisibility`. */
  // 'webkitBackfaceVisibility',
  /** @deprecated This is a legacy alias of `backgroundClip`. */
  // 'webkitBackgroundClip',
  /** @deprecated This is a legacy alias of `backgroundOrigin`. */
  // 'webkitBackgroundOrigin',
  /** @deprecated This is a legacy alias of `backgroundSize`. */
  // 'webkitBackgroundSize',
  /** @deprecated This is a legacy alias of `borderBottomLeftRadius`. */
  // 'webkitBorderBottomLeftRadius',
  /** @deprecated This is a legacy alias of `borderBottomRightRadius`. */
  // 'webkitBorderBottomRightRadius',
  /** @deprecated This is a legacy alias of `borderRadius`. */
  // 'webkitBorderRadius',
  /** @deprecated This is a legacy alias of `borderTopLeftRadius`. */
  // 'webkitBorderTopLeftRadius',
  /** @deprecated This is a legacy alias of `borderTopRightRadius`. */
  // 'webkitBorderTopRightRadius',
  /** @deprecated This is a legacy alias of `boxAlign`. */
  // 'webkitBoxAlign',
  /** @deprecated This is a legacy alias of `boxFlex`. */
  // 'webkitBoxFlex',
  /** @deprecated This is a legacy alias of `boxOrdinalGroup`. */
  // 'webkitBoxOrdinalGroup',
  /** @deprecated This is a legacy alias of `boxOrient`. */
  // 'webkitBoxOrient',
  /** @deprecated This is a legacy alias of `boxPack`. */
  // 'webkitBoxPack',
  /** @deprecated This is a legacy alias of `boxShadow`. */
  // 'webkitBoxShadow',
  /** @deprecated This is a legacy alias of `boxSizing`. */
  // 'webkitBoxSizing',
  /** @deprecated This is a legacy alias of `filter`. */
  // 'webkitFilter',
  /** @deprecated This is a legacy alias of `flex`. */
  // 'webkitFlex',
  /** @deprecated This is a legacy alias of `flexBasis`. */
  // 'webkitFlexBasis',
  /** @deprecated This is a legacy alias of `flexDirection`. */
  // 'webkitFlexDirection',
  /** @deprecated This is a legacy alias of `flexFlow`. */
  // 'webkitFlexFlow',
  /** @deprecated This is a legacy alias of `flexGrow`. */
  // 'webkitFlexGrow',
  /** @deprecated This is a legacy alias of `flexShrink`. */
  // 'webkitFlexShrink',
  /** @deprecated This is a legacy alias of `flexWrap`. */
  // 'webkitFlexWrap',
  /** @deprecated This is a legacy alias of `justifyContent`. */
  // 'webkitJustifyContent',
  // 'webkitLineClamp',
  /** @deprecated This is a legacy alias of `mask`. */
  // 'webkitMask',
  /** @deprecated This is a legacy alias of `maskBorder`. */
  // 'webkitMaskBoxImage',
  /** @deprecated This is a legacy alias of `maskBorderOutset`. */
  // 'webkitMaskBoxImageOutset',
  /** @deprecated This is a legacy alias of `maskBorderRepeat`. */
  // 'webkitMaskBoxImageRepeat',
  /** @deprecated This is a legacy alias of `maskBorderSlice`. */
  // 'webkitMaskBoxImageSlice',
  /** @deprecated This is a legacy alias of `maskBorderSource`. */
  // 'webkitMaskBoxImageSource',
  /** @deprecated This is a legacy alias of `maskBorderWidth`. */
  // 'webkitMaskBoxImageWidth',
  /** @deprecated This is a legacy alias of `maskClip`. */
  // 'webkitMaskClip',
  // 'webkitMaskComposite',
  /** @deprecated This is a legacy alias of `maskImage`. */
  // 'webkitMaskImage',
  /** @deprecated This is a legacy alias of `maskOrigin`. */
  // 'webkitMaskOrigin',
  /** @deprecated This is a legacy alias of `maskPosition`. */
  // 'webkitMaskPosition',
  /** @deprecated This is a legacy alias of `maskRepeat`. */
  // 'webkitMaskRepeat',
  /** @deprecated This is a legacy alias of `maskSize`. */
  // 'webkitMaskSize',
  /** @deprecated This is a legacy alias of `order`. */
  // 'webkitOrder',
  /** @deprecated This is a legacy alias of `perspective`. */
  // 'webkitPerspective',
  /** @deprecated This is a legacy alias of `perspectiveOrigin`. */
  // 'webkitPerspectiveOrigin',
  // 'webkitTextFillColor',
  // 'webkitTextStroke',
  // 'webkitTextStrokeColor',
  // 'webkitTextStrokeWidth',
  /** @deprecated This is a legacy alias of `transform`. */
  // 'webkitTransform',
  /** @deprecated This is a legacy alias of `transformOrigin`. */
  // 'webkitTransformOrigin',
  /** @deprecated This is a legacy alias of `transformStyle`. */
  // 'webkitTransformStyle',
  /** @deprecated This is a legacy alias of `transition`. */
  // 'webkitTransition',
  /** @deprecated This is a legacy alias of `transitionDelay`. */
  // 'webkitTransitionDelay',
  /** @deprecated This is a legacy alias of `transitionDuration`. */
  // 'webkitTransitionDuration',
  /** @deprecated This is a legacy alias of `transitionProperty`. */
  // 'webkitTransitionProperty',
  /** @deprecated This is a legacy alias of `transitionTimingFunction`. */
  // 'webkitTransitionTimingFunction',
  /** @deprecated This is a legacy alias of `userSelect`. */
  // 'webkitUserSelect',
  'whiteSpace',
  'widows',
  'width',
  'willChange',
  'wordBreak',
  'wordSpacing',
  /** @deprecated */
  'wordWrap',
  'writingMode',
  'zIndex',
];
